"""Turtle bot core package."""

from .domain import (
    Candle,
    IndicatorSnapshot,
    Signal,
    SignalKind,
    Side,
    PositionStatus,
    StrategyState,
    TradeOutcome,
    TurtleSystem,
    UnitState,
    PositionState,
)
from .state_store import SQLiteStateStore
from .backtest import (
    AuditEvent,
    BacktestConfig,
    BacktestCosts,
    BacktestEngine,
    BacktestResult,
    BacktestTrade,
    EquityPoint,
    backtest_result_to_dict,
    export_backtest_report_json,
    load_candles_csv,
)
from .toss_client import (
    ACCOUNT_HEADER,
    CandlePage,
    TossApiError,
    TossClient,
    TossCredentials,
    TossHttpResponse,
    TossToken,
)
from .position_sync import (
    BrokerHolding,
    BrokerOrder,
    ReconcileIssue,
    ReconcileResult,
    TossPositionSync,
    normalize_holdings,
    normalize_orders,
    reconcile_positions,
)
from .paper_runtime import (
    GuardCheck,
    GuardResult,
    PaperBrokerSimulator,
    PaperOrderGuard,
    PaperOrderIntent,
    PaperRunResult,
    PaperRuntimeConfig,
    PaperRuntimeScheduler,
    PaperTradingRuntime,
    export_paper_report_json,
    paper_run_result_to_dict,
)
from .operations import (
    DEFAULT_SERVICE_LABEL,
    LaunchdServiceConfig,
    OperationsCheck,
    check_operations_config,
    ensure_runtime_dirs,
    operations_checks_payload,
    paper_service_health,
    render_launchd_plist,
    run_paper_service,
    write_launchd_plist,
)
from .market_calendar import (
    MarketCalendarConfig,
    MarketCalendarGate,
    MarketSessionState,
    parse_market_session,
)
from .toss_market_data import (
    TossMarketDataConfig,
    TossReadOnlyMarketDataProvider,
    extract_price,
)
from .reports import (
    DailyReportConfig,
    build_daily_report,
    export_daily_report_json,
    summarize_runtime_events,
)

__all__ = [
    "Candle",
    "IndicatorSnapshot",
    "Signal",
    "SignalKind",
    "Side",
    "PositionStatus",
    "StrategyState",
    "TradeOutcome",
    "TurtleSystem",
    "UnitState",
    "Unit",
    "SQLiteStateStore",
    "PositionState",
    "AuditEvent",
    "BacktestConfig",
    "BacktestCosts",
    "BacktestEngine",
    "BacktestResult",
    "BacktestTrade",
    "EquityPoint",
    "backtest_result_to_dict",
    "export_backtest_report_json",
    "load_candles_csv",
    "ACCOUNT_HEADER",
    "CandlePage",
    "TossApiError",
    "TossClient",
    "TossCredentials",
    "TossHttpResponse",
    "TossToken",
    "BrokerHolding",
    "BrokerOrder",
    "ReconcileIssue",
    "ReconcileResult",
    "TossPositionSync",
    "normalize_holdings",
    "normalize_orders",
    "reconcile_positions",
    "PaperOrderIntent",
    "PaperRunResult",
    "PaperRuntimeConfig",
    "GuardCheck",
    "GuardResult",
    "PaperBrokerSimulator",
    "PaperOrderGuard",
    "PaperRuntimeScheduler",
    "PaperTradingRuntime",
    "export_paper_report_json",
    "paper_run_result_to_dict",
    "DEFAULT_SERVICE_LABEL",
    "LaunchdServiceConfig",
    "OperationsCheck",
    "check_operations_config",
    "ensure_runtime_dirs",
    "operations_checks_payload",
    "paper_service_health",
    "render_launchd_plist",
    "run_paper_service",
    "write_launchd_plist",
    "MarketCalendarConfig",
    "MarketCalendarGate",
    "MarketSessionState",
    "parse_market_session",
    "TossMarketDataConfig",
    "TossReadOnlyMarketDataProvider",
    "extract_price",
    "DailyReportConfig",
    "build_daily_report",
    "export_daily_report_json",
    "summarize_runtime_events",
]

Unit = UnitState

__version__ = "0.1.0"
